version: "3"
services:
  identidock:
    image: jooos/avatar
    ports:
     - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    links:
      - dnmonster
      - redis
  dnmonster:
    image: jooos/dnmonster
  redis:
    image: redis
